// <auto-generated />
using System;
using FiscalHost.Api.CR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiscalHost.Api.CR.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607060000_AddLlavesCriptograficas")]
    partial class AddLlavesCriptograficas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.ActividadEconomica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ActividadesEconomicas");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.AuditoriaConfiguracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ConfiguracionTributariaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValorAnterior")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValorNuevo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionTributariaId");

                    b.ToTable("AuditoriasConfiguracion");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.AuditoriaLlave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<int>("LlaveCriptograficaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LlaveCriptograficaId");

                    b.ToTable("AuditoriasLlave");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.ConfiguracionTributaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadEconomicaId")
                        .HasColumnType("int");

                    b.Property<string>("AnfitrionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DireccionFiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nise")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TribuCr")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ActividadEconomicaId");

                    b.ToTable("ConfiguracionesTributarias");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.LlaveCriptografica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("AnfitrionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("ContenidoCifrado")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.HasKey("Id");

                    b.ToTable("LlavesCriptograficas");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.AuditoriaConfiguracion", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.ConfiguracionTributaria", "ConfiguracionTributaria")
                        .WithMany("Auditorias")
                        .HasForeignKey("ConfiguracionTributariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionTributaria");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.AuditoriaLlave", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.LlaveCriptografica", "LlaveCriptografica")
                        .WithMany("Auditorias")
                        .HasForeignKey("LlaveCriptograficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LlaveCriptografica");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.ConfiguracionTributaria", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.ActividadEconomica", "ActividadEconomica")
                        .WithMany("Configuraciones")
                        .HasForeignKey("ActividadEconomicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActividadEconomica");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.ActividadEconomica", b =>
                {
                    b.Navigation("Configuraciones");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.ConfiguracionTributaria", b =>
                {
                    b.Navigation("Auditorias");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.LlaveCriptografica", b =>
                {
                    b.Navigation("Auditorias");
                });
#pragma warning restore 612, 618
        }
    }
}
