// <auto-generated />
using System;
using System.Net;
using FiscalHost.Api.CR.Data;
using FiscalHost.Api.CR.Models.Enums.Audit;
using FiscalHost.Api.CR.Models.Enums.Communication;
using FiscalHost.Api.CR.Models.Enums.Identity;
using FiscalHost.Api.CR.Models.Enums.Operations;
using FiscalHost.Api.CR.Models.Enums.TaxIntelligence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiscalHost.Api.CR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720161854_AddD104EnumSql")]
    partial class AddD104EnumSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fiscalhost_db")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_llave", "fiscalhost_db", new[] { "ACTIVA", "EXPIRADA", "REVOCADA" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "canal_notificacion", new[] { "CORREO", "PLATAFORMA", "AMBOS" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "clasificacion_fiscal", new[] { "GRAVADO", "EXENTO", "GRAVADO_CON_RETENCION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "clasificacion_iva", new[] { "GRAVADO_13", "EXENTO" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "estado_declaracion", new[] { "BORRADOR", "CALCULADO", "VALIDADO", "EXPORTADO", "PRESENTADO" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "estado_importacion", new[] { "PENDIENTE", "PROCESANDO", "COMPLETADO", "COMPLETADO_PARCIAL", "RECHAZADO" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "estado_llave", new[] { "ACTIVA", "EXPIRADA", "REVOCADA" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "estado_notificacion", new[] { "PENDIENTE", "ENVIADA", "ENTREGADA", "FALLIDA", "LEIDA" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "estado_obligacion", new[] { "VIGENTE", "VENCIDA", "PAGADA", "EN_ARREGLO" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "estado_ocr", new[] { "pendiente", "procesado", "ilegible", "sin_procesar" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "estado_usuario", new[] { "PENDIENTE_ACTIVACION", "ACTIVO", "INACTIVO", "BLOQUEADO", "ELIMINADO" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "estado_validacion", new[] { "PENDIENTE", "VALIDO", "RECHAZADO", "DUPLICADO" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "fuente_ingreso", new[] { "NACIONAL", "EXTRANJERA" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "fuente_registro", new[] { "IMPORTACION_CSV", "MANUAL", "RECONSTRUCCION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "operacion_auditoria", new[] { "insert", "update", "delete", "login", "logout", "export", "reclasificacion", "cambio_regimen", "cambio_actividad_economica" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "plataforma_origen", new[] { "AIRBNB", "BOOKING", "VRBO", "DIRECTA", "OTRA" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "regimen_tributario", new[] { "CAPITAL_INMOBILIARIO", "UTILIDADES" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "rol_usuario", new[] { "ANFITRION", "CONTADOR", "ADMINISTRADOR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "tipo_alerta", new[] { "VENCIMIENTO_15_DIAS", "VENCIMIENTO_10_DIAS", "VENCIMIENTO_7_DIAS", "VENCIMIENTO_3_DIAS", "VENCIMIENTO_1_DIA", "VENCIMIENTO_EXPIRADO", "LLAVE_POR_VENCER", "INFORMATIVA", "SEGURIDAD" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "tipo_formulario", new[] { "D150", "D116", "D176", "D104" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "tipo_identificacion", new[] { "FISICA", "JURIDICA", "DIMEX", "NITE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fiscalhost_db", "tipo_moneda", new[] { "CRC", "USD" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Audit.AuditoriaConfiguracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConfiguracionTributariaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValorAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValorNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionTributariaId");

                    b.ToTable("auditoria_configuracion", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Audit.AuditoriaLlave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LlaveCriptograficaId")
                        .HasColumnType("integer");

                    b.Property<Guid>("LlaveCriptograficaLlaveId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LlaveCriptograficaLlaveId");

                    b.ToTable("auditoria_llave", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Audit.AuditoriaOperacion", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<string[]>("CamposModificados")
                        .HasColumnType("text[]")
                        .HasColumnName("campos_modificados");

                    b.Property<string>("CorreoUsuario")
                        .HasColumnType("text")
                        .HasColumnName("correo_usuario");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<IPAddress>("IpOrigen")
                        .HasColumnType("inet")
                        .HasColumnName("ip_origen");

                    b.Property<string>("Justificacion")
                        .HasColumnType("text")
                        .HasColumnName("justificacion");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<OperacionAuditoria>("Operacion")
                        .HasColumnType("fiscalhost_db.operacion_auditoria")
                        .HasColumnName("operacion");

                    b.Property<Guid?>("RegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("registro_id");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<RolUsuario?>("RolUsuario")
                        .HasColumnType("fiscalhost_db.rol_usuario")
                        .HasColumnName("rol_usuario");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tabla_afectada");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("AuditId");

                    b.ToTable("audit_log", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Audit.LlaveCriptografica", b =>
                {
                    b.Property<Guid>("LlaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("llave_id");

                    b.Property<string>("EmisorCertificado")
                        .HasColumnType("text")
                        .HasColumnName("emisor_certificado");

                    b.Property<EstadoLlave>("Estado")
                        .HasColumnType("fiscalhost_db.estado_llave")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<DateTime?>("FechaEmisionCertificado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision_certificado");

                    b.Property<DateTime?>("FechaExpiracionCertificado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion_certificado");

                    b.Property<string>("HashIntegridad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_integridad");

                    b.Property<string>("HuellaDigitalCertificado")
                        .HasColumnType("text")
                        .HasColumnName("huella_digital_certificado");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("ReferenciaKeyVault")
                        .HasColumnType("text")
                        .HasColumnName("referencia_key_vault");

                    b.Property<string>("RutaBlobStorage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruta_blob_storage");

                    b.Property<DateTime?>("UltimaActualizacionContrasena")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion_contrasena");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("LlaveId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("llave_criptografica", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Communication.Alerta", b =>
                {
                    b.Property<Guid>("AlertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("alerta_id");

                    b.Property<string>("AccionSugerida")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("accion_sugerida");

                    b.Property<CanalNotificacion>("Canal")
                        .HasColumnType("fiscalhost_db.canal_notificacion")
                        .HasColumnName("canal");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorEnvio")
                        .HasColumnType("text")
                        .HasColumnName("error_envio");

                    b.Property<EstadoNotificacion>("Estado")
                        .HasColumnType("fiscalhost_db.estado_notificacion")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<DateTimeOffset?>("FechaLectura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_lectura");

                    b.Property<DateTimeOffset>("FechaProgramada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_programada");

                    b.Property<short>("IntentosEnvio")
                        .HasColumnType("smallint")
                        .HasColumnName("intentos_envio");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<decimal?>("MontoEstimado")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_estimado");

                    b.Property<Guid?>("ObligacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("obligacion_id");

                    b.Property<short>("Prioridad")
                        .HasColumnType("smallint")
                        .HasColumnName("prioridad");

                    b.Property<TipoAlerta>("TipoAlerta")
                        .HasColumnType("fiscalhost_db.tipo_alerta")
                        .HasColumnName("tipo_alerta");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("AlertaId");

                    b.HasIndex("ObligacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("alerta", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Communication.ContenidoEducativo", b =>
                {
                    b.Property<Guid>("ContenidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("contenido_id");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("ContenidoHtml")
                        .HasColumnType("text")
                        .HasColumnName("contenido_html");

                    b.Property<string>("ContenidoMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido_markdown");

                    b.Property<bool>("EsTutorialPrimerUso")
                        .HasColumnType("boolean")
                        .HasColumnName("es_tutorial_primer_uso");

                    b.Property<int>("OrdenDisplay")
                        .HasColumnType("integer")
                        .HasColumnName("orden_display");

                    b.Property<bool>("Publicado")
                        .HasColumnType("boolean")
                        .HasColumnName("publicado");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("ContenidoId");

                    b.HasIndex("AutorId");

                    b.ToTable("contenido_educativo", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.AccesoContador", b =>
                {
                    b.Property<Guid>("AccesoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("acceso_id");

                    b.Property<Guid>("AnfitrionId")
                        .HasColumnType("uuid")
                        .HasColumnName("anfitrion_id");

                    b.Property<Guid?>("ContadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("contador_id");

                    b.Property<string>("CorreoContador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo_contador");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaAceptacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aceptacion");

                    b.Property<DateTimeOffset?>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTimeOffset>("FechaInvitacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_invitacion");

                    b.Property<DateTimeOffset?>("FechaRevocacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_revocacion");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permisos");

                    b.HasKey("AccesoId");

                    b.HasIndex("AnfitrionId");

                    b.HasIndex("ContadorId");

                    b.ToTable("acceso_contador", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.ConfiguracionTributaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadEconomicaCodigo")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AnfitrionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoActividad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DireccionFiscal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TribuCr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActividadEconomicaCodigo");

                    b.ToTable("ConfiguracionTributaria", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.PerfilTributario", b =>
                {
                    b.Property<Guid>("PerfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("CodigoActividadEconomica")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_actividad_economica");

                    b.Property<string>("DatosComplementarios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_complementarios");

                    b.Property<string>("DescripcionActividad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_actividad");

                    b.Property<string>("DireccionFiscal")
                        .HasColumnType("text")
                        .HasColumnName("direccion_fiscal");

                    b.Property<bool>("EsDomicilioValidado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_domicilio_validado");

                    b.Property<DateTime?>("FechaInicioActividad")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_actividad");

                    b.Property<DateTime?>("FechaInscripcionHacienda")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inscripcion_hacienda");

                    b.Property<string>("Nise")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nise");

                    b.Property<RegimenTributario>("RegimenTributario")
                        .HasColumnType("fiscalhost_db.regimen_tributario")
                        .HasColumnName("regimen_tributario");

                    b.Property<string>("TribuCr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tribu_cr");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("PerfilId");

                    b.HasIndex("CodigoActividadEconomica");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("perfil_tributario", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.Propiedad", b =>
                {
                    b.Property<Guid>("PropiedadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("propiedad_id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Canton")
                        .HasColumnType("text")
                        .HasColumnName("canton");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .HasColumnType("text")
                        .HasColumnName("distrito");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroFinca")
                        .HasColumnType("text")
                        .HasColumnName("numero_finca");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("provincia");

                    b.Property<TipoMoneda?>("TipoMonedaValor")
                        .HasColumnType("fiscalhost_db.tipo_moneda")
                        .HasColumnName("tipo_moneda_valor");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal?>("ValorFiscal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_fiscal");

                    b.HasKey("PropiedadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("propiedad", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo_electronico");

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("boolean")
                        .HasColumnName("correo_verificado");

                    b.Property<bool>("EsUsuarioNuevo")
                        .HasColumnType("boolean")
                        .HasColumnName("es_usuario_nuevo");

                    b.Property<EstadoUsuario>("Estado")
                        .HasColumnType("fiscalhost_db.estado_usuario")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaActivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_activacion");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_identificacion");

                    b.Property<string>("PreferenciasNotificacion")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferencias_notificacion");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razon_social");

                    b.Property<RolUsuario>("RolPrincipal")
                        .HasColumnType("fiscalhost_db.rol_usuario")
                        .HasColumnName("rol_principal");

                    b.Property<TipoIdentificacion>("TipoIdentificacion")
                        .HasColumnType("fiscalhost_db.tipo_identificacion")
                        .HasColumnName("tipo_identificacion");

                    b.Property<DateTimeOffset?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("UsuarioId");

                    b.ToTable("usuario", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.AuditoriaClasificacionIngreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("auditoria_clasificacion_ingreso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClasificacionIngresoId")
                        .HasColumnType("integer")
                        .HasColumnName("clasificacion_ingreso_id");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evento");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("justificacion");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValorAnterior")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id");

                    b.HasIndex("ClasificacionIngresoId");

                    b.ToTable("auditoria_clasificacion_ingreso", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.ClasificacionIngreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clasificacion_ingreso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnfitrionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("anfitrion_id");

                    b.Property<decimal>("BaseImponibleRenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_imponible_renta");

                    b.Property<ClasificacionIva>("ClasificacionIva")
                        .HasColumnType("fiscalhost_db.clasificacion_iva")
                        .HasColumnName("clasificacion_iva");

                    b.Property<int>("DiasEstancia")
                        .HasColumnType("integer")
                        .HasColumnName("dias_estancia");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrada");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_salida");

                    b.Property<FuenteIngreso>("FuenteIngreso")
                        .HasColumnType("fiscalhost_db.fuente_ingreso")
                        .HasColumnName("fuente_ingreso");

                    b.Property<bool>("HuespedResidente")
                        .HasColumnType("boolean")
                        .HasColumnName("huesped_residente");

                    b.Property<decimal>("ImpuestoRenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("impuesto_renta");

                    b.Property<string>("JustificacionManual")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("justificacion_manual");

                    b.Property<decimal>("MontoBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_bruto");

                    b.Property<decimal>("MontoIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_iva");

                    b.Property<decimal>("MontoRetencion")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_retencion");

                    b.Property<decimal>("NetoAnfitrion")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("neto_anfitrion");

                    b.Property<bool>("ReclasificadoManualmente")
                        .HasColumnType("boolean")
                        .HasColumnName("reclasificado_manualmente");

                    b.Property<bool>("TieneFacturaElectronicaNacional")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_factura_electronica_nacional");

                    b.HasKey("Id");

                    b.HasIndex("AnfitrionId");

                    b.ToTable("clasificacion_ingreso", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.Gasto", b =>
                {
                    b.Property<Guid>("GastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("gasto_id");

                    b.Property<string>("ClaveNumericaHacienda")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clave_numerica_hacienda");

                    b.Property<string>("DatosExtraidosOcr")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_extraidos_ocr");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsCreditoFiscalValido")
                        .HasColumnType("boolean")
                        .HasColumnName("es_credito_fiscal_valido");

                    b.Property<bool>("EsDeducibleRenta")
                        .HasColumnType("boolean")
                        .HasColumnName("es_deducible_renta");

                    b.Property<EstadoOcr?>("EstadoOcr")
                        .HasColumnType("fiscalhost_db.estado_ocr")
                        .HasColumnName("estado_ocr");

                    b.Property<EstadoValidacion>("EstadoValidacion")
                        .HasColumnType("fiscalhost_db.estado_validacion")
                        .HasColumnName("estado_validacion");

                    b.Property<string>("EvidenciaNombreArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("evidencia_nombre_archivo");

                    b.Property<long?>("EvidenciaTamanioBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("evidencia_tamanio_bytes");

                    b.Property<string>("EvidenciaTipoMime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("evidencia_tipo_mime");

                    b.Property<string>("EvidenciaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("evidencia_url");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<FuenteRegistro>("FuenteRegistro")
                        .HasColumnType("fiscalhost_db.fuente_registro")
                        .HasColumnName("fuente_registro");

                    b.Property<string>("HashUnicoComprobante")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_unico_comprobante");

                    b.Property<TipoMoneda>("Moneda")
                        .HasColumnType("fiscalhost_db.tipo_moneda")
                        .HasColumnName("moneda");

                    b.Property<decimal>("MontoColones")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_colones");

                    b.Property<decimal>("MontoIvaSoportado")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_iva_soportado");

                    b.Property<decimal?>("MontoNeto")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasColumnName("monto_neto");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_factura");

                    b.Property<string>("ObservacionesValidacion")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_validacion");

                    b.Property<short>("PeriodoFiscalAnio")
                        .HasColumnType("smallint")
                        .HasColumnName("periodo_fiscal_anio");

                    b.Property<short>("PeriodoFiscalMes")
                        .HasColumnType("smallint")
                        .HasColumnName("periodo_fiscal_mes");

                    b.Property<Guid?>("PropiedadId")
                        .HasColumnType("uuid")
                        .HasColumnName("propiedad_id");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proveedor");

                    b.Property<decimal?>("TipoCambio")
                        .HasColumnType("numeric")
                        .HasColumnName("tipo_cambio");

                    b.Property<string>("TipoGasto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_gasto");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("GastoId");

                    b.HasIndex("PropiedadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("gasto", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.GastoOperativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnfitrionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComprobanteUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaGasto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("gasto_operativo", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.ImportacionMasiva", b =>
                {
                    b.Property<Guid>("ImportacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("importacion_id");

                    b.Property<string>("ArchivoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("archivo_url");

                    b.Property<string>("DetalleErrores")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle_errores");

                    b.Property<EstadoImportacion>("Estado")
                        .HasColumnType("fiscalhost_db.estado_importacion")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaCarga")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<DateTimeOffset?>("FechaFinProcesamiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin_procesamiento");

                    b.Property<DateTimeOffset?>("FechaInicioProcesamiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_procesamiento");

                    b.Property<string>("NombreArchivoOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_archivo_original");

                    b.Property<string>("PlantillaUtilizada")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plantilla_utilizada");

                    b.Property<PlataformaOrigen?>("PlataformaOrigen")
                        .HasColumnType("fiscalhost_db.plataforma_origen")
                        .HasColumnName("plataforma_origen");

                    b.Property<int?>("RegistrosConError")
                        .HasColumnType("integer")
                        .HasColumnName("registros_con_error");

                    b.Property<int?>("RegistrosExitosos")
                        .HasColumnType("integer")
                        .HasColumnName("registros_exitosos");

                    b.Property<string>("ReporteErroresUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reporte_errores_url");

                    b.Property<long?>("TamanioBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanio_bytes");

                    b.Property<string>("TipoImportacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_importacion");

                    b.Property<int?>("TotalRegistros")
                        .HasColumnType("integer")
                        .HasColumnName("total_registros");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("ImportacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("importacion_masiva", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.Reserva", b =>
                {
                    b.Property<Guid>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_id");

                    b.Property<ClasificacionFiscal>("ClasificacionFiscal")
                        .HasColumnType("fiscalhost_db.clasificacion_fiscal")
                        .HasColumnName("clasificacion_fiscal");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTimeOffset?>("FechaReclasificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_reclasificacion");

                    b.Property<bool>("FueReclasificada")
                        .HasColumnType("boolean")
                        .HasColumnName("fue_reclasificada");

                    b.Property<FuenteRegistro>("FuenteRegistro")
                        .HasColumnType("fiscalhost_db.fuente_registro")
                        .HasColumnName("fuente_registro");

                    b.Property<string>("IdentificacionHuesped")
                        .HasColumnType("text")
                        .HasColumnName("identificacion_huesped");

                    b.Property<Guid?>("ImportacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("importacion_id");

                    b.Property<string>("JustificacionReclasificacion")
                        .HasColumnType("text")
                        .HasColumnName("justificacion_reclasificacion");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<TipoMoneda>("Moneda")
                        .HasColumnType("fiscalhost_db.tipo_moneda")
                        .HasColumnName("moneda");

                    b.Property<decimal>("MontoBruto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_bruto");

                    b.Property<decimal>("MontoColones")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_colones");

                    b.Property<decimal>("MontoExento")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_exento");

                    b.Property<decimal>("MontoGravado")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_gravado");

                    b.Property<decimal>("MontoIvaCalculado")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_iva_calculado");

                    b.Property<string>("NombreHuesped")
                        .HasColumnType("text")
                        .HasColumnName("nombre_huesped");

                    b.Property<string>("PaisOrigenHuesped")
                        .HasColumnType("text")
                        .HasColumnName("pais_origen_huesped");

                    b.Property<short>("PeriodoFiscalAnio")
                        .HasColumnType("smallint")
                        .HasColumnName("periodo_fiscal_anio");

                    b.Property<short>("PeriodoFiscalMes")
                        .HasColumnType("smallint")
                        .HasColumnName("periodo_fiscal_mes");

                    b.Property<PlataformaOrigen>("PlataformaOrigen")
                        .HasColumnType("fiscalhost_db.plataforma_origen")
                        .HasColumnName("plataforma_origen");

                    b.Property<Guid?>("PropiedadId")
                        .HasColumnType("uuid")
                        .HasColumnName("propiedad_id");

                    b.Property<string>("ReferenciaPlataforma")
                        .HasColumnType("text")
                        .HasColumnName("referencia_plataforma");

                    b.Property<decimal>("RetencionExtranjera")
                        .HasColumnType("numeric")
                        .HasColumnName("retencion_extranjera");

                    b.Property<decimal>("TipoCambio")
                        .HasColumnType("numeric")
                        .HasColumnName("tipo_cambio");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid?>("UsuarioReclasificacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_reclasificacion_id");

                    b.HasKey("ReservaId");

                    b.HasIndex("ImportacionId");

                    b.HasIndex("PropiedadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("reserva", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.ReservaDirecta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnfitrionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Huesped")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("reserva_directa", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.CalculoFiscal", b =>
                {
                    b.Property<Guid>("CalculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("calculo_id");

                    b.Property<bool>("BorradorGenerado")
                        .HasColumnType("boolean")
                        .HasColumnName("borrador_generado");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditoFiscal")
                        .HasColumnType("numeric")
                        .HasColumnName("credito_fiscal");

                    b.Property<decimal>("DebitoFiscal")
                        .HasColumnType("numeric")
                        .HasColumnName("debito_fiscal");

                    b.Property<decimal?>("DeduccionAplicada")
                        .HasColumnType("numeric")
                        .HasColumnName("deduccion_aplicada");

                    b.Property<string>("DetalleCalculo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle_calculo");

                    b.Property<EstadoDeclaracion>("Estado")
                        .HasColumnType("fiscalhost_db.estado_declaracion")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaGeneracionBorrador")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion_borrador");

                    b.Property<decimal?>("ImpuestoRenta")
                        .HasColumnType("numeric")
                        .HasColumnName("impuesto_renta");

                    b.Property<decimal>("IvaNeto")
                        .HasColumnType("numeric")
                        .HasColumnName("iva_neto");

                    b.Property<decimal>("MontoTotalAPagar")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total_a_pagar");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uuid")
                        .HasColumnName("periodo_id");

                    b.Property<RegimenTributario?>("RegimenAplicado")
                        .HasColumnType("fiscalhost_db.regimen_tributario")
                        .HasColumnName("regimen_aplicado");

                    b.Property<decimal?>("RentaBruta")
                        .HasColumnType("numeric")
                        .HasColumnName("renta_bruta");

                    b.Property<decimal?>("RentaNeta")
                        .HasColumnType("numeric")
                        .HasColumnName("renta_neta");

                    b.Property<decimal?>("RetencionesAcreditadas")
                        .HasColumnType("numeric")
                        .HasColumnName("retenciones_acreditadas");

                    b.Property<decimal>("SaldoFavorAnterior")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_favor_anterior");

                    b.Property<decimal>("SaldoFavorResultante")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_favor_resultante");

                    b.Property<TipoFormulario>("TipoFormulario")
                        .HasColumnType("fiscalhost_db.tipo_formulario")
                        .HasColumnName("tipo_formulario");

                    b.Property<decimal>("TotalIngresosBrutos")
                        .HasColumnType("numeric")
                        .HasColumnName("total_ingresos_brutos");

                    b.Property<decimal>("TotalIngresosExentos")
                        .HasColumnType("numeric")
                        .HasColumnName("total_ingresos_exentos");

                    b.Property<decimal>("TotalIngresosGravados")
                        .HasColumnType("numeric")
                        .HasColumnName("total_ingresos_gravados");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("CalculoId");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("calculo_fiscal", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.CatalogoActividadEconomica", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaVigenciaDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vigencia_desde");

                    b.Property<DateTime?>("FechaVigenciaHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vigencia_hasta");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.Property<decimal>("TarifaIva")
                        .HasColumnType("numeric")
                        .HasColumnName("tarifa_iva");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasColumnName("vigente");

                    b.HasKey("Codigo");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("catalogo_actividad_economica", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.Exportacion", b =>
                {
                    b.Property<Guid>("ExportacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exportacion_id");

                    b.Property<string>("ArchivoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("archivo_url");

                    b.Property<Guid?>("CalculoFiscalCalculoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CalculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("calculo_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EstaProtegido")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_protegido");

                    b.Property<DateTimeOffset?>("ExpiraAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_at");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("formato");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<long?>("TamanioBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanio_bytes");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_contenido");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("ExportacionId");

                    b.HasIndex("CalculoFiscalCalculoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("exportacion", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.ObligacionTributaria", b =>
                {
                    b.Property<Guid>("ObligacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("obligacion_id");

                    b.Property<Guid?>("CalculoFiscalCalculoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CalculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("calculo_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<EstadoObligacion>("Estado")
                        .HasColumnType("fiscalhost_db.estado_obligacion")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaPago")
                        .HasColumnType("date")
                        .HasColumnName("fecha_pago");

                    b.Property<DateTimeOffset?>("FechaUltimoCalculoInteres")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultimo_calculo_interes");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<string>("HistorialIntereses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("historial_intereses");

                    b.Property<decimal>("MontoCapital")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_capital");

                    b.Property<decimal>("MontoInteresesAcumulados")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_intereses_acumulados");

                    b.Property<decimal>("MontoMulta")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_multa");

                    b.Property<decimal>("MontoTotalActualizado")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total_actualizado");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uuid")
                        .HasColumnName("periodo_id");

                    b.Property<decimal?>("TasaInteresAplicada")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_interes_aplicada");

                    b.Property<TipoFormulario>("TipoFormulario")
                        .HasColumnType("fiscalhost_db.tipo_formulario")
                        .HasColumnName("tipo_formulario");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("ObligacionId");

                    b.HasIndex("CalculoFiscalCalculoId");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("obligacion_tributaria", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.PeriodoFiscal", b =>
                {
                    b.Property<Guid>("PeriodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("periodo_id");

                    b.Property<short>("Anio")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.Property<decimal>("DeduccionPlanaCapital")
                        .HasColumnType("numeric")
                        .HasColumnName("deduccion_plana_capital");

                    b.Property<DateTime>("FechaFinPeriodo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin_periodo");

                    b.Property<DateTime>("FechaInicioPeriodo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_periodo");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<short>("Mes")
                        .HasColumnType("smallint")
                        .HasColumnName("mes");

                    b.Property<string>("NormativaAplicable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normativa_aplicable");

                    b.Property<decimal>("TarifaIva")
                        .HasColumnType("numeric")
                        .HasColumnName("tarifa_iva");

                    b.Property<decimal>("TarifaRentaCapital")
                        .HasColumnType("numeric")
                        .HasColumnName("tarifa_renta_capital");

                    b.Property<decimal?>("TasaInteresMoraAnual")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_interes_mora_anual");

                    b.Property<TipoFormulario>("TipoFormulario")
                        .HasColumnType("fiscalhost_db.tipo_formulario")
                        .HasColumnName("tipo_formulario");

                    b.HasKey("PeriodoId");

                    b.ToTable("periodo_fiscal", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.SancionAutoliquidacion", b =>
                {
                    b.Property<Guid>("SancionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sancion_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("DetalleCalculo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle_calculo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaOmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_omision");

                    b.Property<decimal>("InteresesAcumulados")
                        .HasColumnType("numeric")
                        .HasColumnName("intereses_acumulados");

                    b.Property<decimal>("MontoBaseAdeudado")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_base_adeudado");

                    b.Property<decimal>("MontoReduccion")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_reduccion");

                    b.Property<decimal>("MontoTotalPagar")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total_pagar");

                    b.Property<decimal>("MultaBaseCalculada")
                        .HasColumnType("numeric")
                        .HasColumnName("multa_base_calculada");

                    b.Property<decimal>("MultaReducida")
                        .HasColumnType("numeric")
                        .HasColumnName("multa_reducida");

                    b.Property<Guid?>("ObligacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("obligacion_id");

                    b.Property<decimal>("PorcentajeReduccion")
                        .HasColumnType("numeric")
                        .HasColumnName("porcentaje_reduccion");

                    b.Property<string>("TipoSancion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_sancion");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("SancionId");

                    b.HasIndex("ObligacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sancion_autoliquidacion", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.SimulacionFiscal", b =>
                {
                    b.Property<Guid>("SimulacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("simulacion_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("ParametrosEntrada")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parametros_entrada");

                    b.Property<short>("PeriodoBaseAnio")
                        .HasColumnType("smallint")
                        .HasColumnName("periodo_base_anio");

                    b.Property<short?>("PeriodoBaseMes")
                        .HasColumnType("smallint")
                        .HasColumnName("periodo_base_mes");

                    b.Property<string>("Resultados")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resultados");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("SimulacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("simulacion_fiscal", "fiscalhost_db");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Audit.AuditoriaConfiguracion", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.ConfiguracionTributaria", "ConfiguracionTributaria")
                        .WithMany("Auditorias")
                        .HasForeignKey("ConfiguracionTributariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionTributaria");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Audit.AuditoriaLlave", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Audit.LlaveCriptografica", "LlaveCriptografica")
                        .WithMany("Auditorias")
                        .HasForeignKey("LlaveCriptograficaLlaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LlaveCriptografica");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Audit.LlaveCriptografica", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", null)
                        .WithMany("LlavesCriptograficas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Communication.Alerta", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.ObligacionTributaria", "Obligacion")
                        .WithMany("Alertas")
                        .HasForeignKey("ObligacionId");

                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obligacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Communication.ContenidoEducativo", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Autor")
                        .WithMany("ContenidosEducativos")
                        .HasForeignKey("AutorId");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.AccesoContador", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Anfitrion")
                        .WithMany("AccesosAnfitrion")
                        .HasForeignKey("AnfitrionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Contador")
                        .WithMany("AccesosContador")
                        .HasForeignKey("ContadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Anfitrion");

                    b.Navigation("Contador");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.ConfiguracionTributaria", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.CatalogoActividadEconomica", "ActividadEconomica")
                        .WithMany()
                        .HasForeignKey("ActividadEconomicaCodigo");

                    b.Navigation("ActividadEconomica");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.PerfilTributario", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.CatalogoActividadEconomica", "ActividadEconomica")
                        .WithMany("PerfilesTributarios")
                        .HasForeignKey("CodigoActividadEconomica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Usuario")
                        .WithOne("PerfilTributario")
                        .HasForeignKey("FiscalHost.Api.CR.Models.Entities.Identity.PerfilTributario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActividadEconomica");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.Propiedad", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Usuario")
                        .WithMany("Propiedades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.AuditoriaClasificacionIngreso", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Operations.ClasificacionIngreso", "ClasificacionIngreso")
                        .WithMany("Auditorias")
                        .HasForeignKey("ClasificacionIngresoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClasificacionIngreso");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.Gasto", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Propiedad", "Propiedad")
                        .WithMany("Gastos")
                        .HasForeignKey("PropiedadId");

                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Usuario")
                        .WithMany("Gastos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.ImportacionMasiva", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Usuario")
                        .WithMany("Importaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.Reserva", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Operations.ImportacionMasiva", "Importacion")
                        .WithMany("Reservas")
                        .HasForeignKey("ImportacionId");

                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Propiedad", "Propiedad")
                        .WithMany("Reservas")
                        .HasForeignKey("PropiedadId");

                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Importacion");

                    b.Navigation("Propiedad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.CalculoFiscal", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.PeriodoFiscal", "Periodo")
                        .WithMany("CalculosFiscales")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Usuario")
                        .WithMany("CalculosFiscales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Periodo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.Exportacion", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.CalculoFiscal", "CalculoFiscal")
                        .WithMany("Exportaciones")
                        .HasForeignKey("CalculoFiscalCalculoId");

                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Usuario")
                        .WithMany("Exportaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculoFiscal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.ObligacionTributaria", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.CalculoFiscal", "CalculoFiscal")
                        .WithMany("Obligaciones")
                        .HasForeignKey("CalculoFiscalCalculoId");

                    b.HasOne("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.PeriodoFiscal", "Periodo")
                        .WithMany("Obligaciones")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Usuario")
                        .WithMany("Obligaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculoFiscal");

                    b.Navigation("Periodo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.SancionAutoliquidacion", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.ObligacionTributaria", "Obligacion")
                        .WithMany("Sanciones")
                        .HasForeignKey("ObligacionId");

                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obligacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.SimulacionFiscal", b =>
                {
                    b.HasOne("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", "Usuario")
                        .WithMany("SimulacionesFiscales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Audit.LlaveCriptografica", b =>
                {
                    b.Navigation("Auditorias");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.ConfiguracionTributaria", b =>
                {
                    b.Navigation("Auditorias");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.Propiedad", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Identity.Usuario", b =>
                {
                    b.Navigation("AccesosAnfitrion");

                    b.Navigation("AccesosContador");

                    b.Navigation("Alertas");

                    b.Navigation("CalculosFiscales");

                    b.Navigation("ContenidosEducativos");

                    b.Navigation("Exportaciones");

                    b.Navigation("Gastos");

                    b.Navigation("Importaciones");

                    b.Navigation("LlavesCriptograficas");

                    b.Navigation("Obligaciones");

                    b.Navigation("PerfilTributario");

                    b.Navigation("Propiedades");

                    b.Navigation("Reservas");

                    b.Navigation("SimulacionesFiscales");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.ClasificacionIngreso", b =>
                {
                    b.Navigation("Auditorias");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.Operations.ImportacionMasiva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.CalculoFiscal", b =>
                {
                    b.Navigation("Exportaciones");

                    b.Navigation("Obligaciones");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.CatalogoActividadEconomica", b =>
                {
                    b.Navigation("PerfilesTributarios");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.ObligacionTributaria", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Sanciones");
                });

            modelBuilder.Entity("FiscalHost.Api.CR.Models.Entities.TaxIntelligence.PeriodoFiscal", b =>
                {
                    b.Navigation("CalculosFiscales");

                    b.Navigation("Obligaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
